all:
	$(DEVKITARM)/bin/grit 00-block.bmp
	$(DEVKITARM)/bin/grit 01-crate.bmp
	$(DEVKITARM)/bin/grit 02-boxman.bmp
	$(DEVKITARM)/bin/grit 03-bgTiles.bmp
	$(DEVKITARM)/bin/grit 04-plus.bmp

clean:
	rm -f *.bin
